/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.view;

import com.gf.controller.OrganizadorController;
import com.gf.entities.Organizador;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author canmonal
 */
/**
 * Esta clase representa la vista de la aplicación de escritorio.
 */
public class vista extends javax.swing.JFrame {

    private OrganizadorController controller;

    /**
     * Crea una nueva instancia de la clase Vista.
     */
    public vista() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Java Desktop App");
        setSize(525, 355);
        setLocationRelativeTo(null);

        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        obtenerOrganizadoresButton = new javax.swing.JButton();
        eliminarOrganizadorButton = new javax.swing.JButton();
        agregarOrganizadorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setMinimumSize(new java.awt.Dimension(521, 315));
        jPanel.setPreferredSize(new java.awt.Dimension(512, 315));
        jPanel.setLayout(new java.awt.BorderLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setMinimumSize(new java.awt.Dimension(521, 315));
        jScrollPane1.setViewportView(textArea);

        jPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        obtenerOrganizadoresButton.setText("Obtener Organizadores");
        obtenerOrganizadoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerOrganizadoresButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(obtenerOrganizadoresButton);

        eliminarOrganizadorButton.setText("Eliminar Organizador");
        eliminarOrganizadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarOrganizadorButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(eliminarOrganizadorButton);

        agregarOrganizadorButton.setText("Insertar Organizador");
        agregarOrganizadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarOrganizadorButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(agregarOrganizadorButton);

        jPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Establece el controlador para la vista.
     *
     * @param controller El controlador a establecer
     */
    public void setController(OrganizadorController controller) {
        this.controller = controller;
    }

    /**
     * Muestra los organizadores en el área de texto de la vista.
     */
    public void mostrarOrganizadores() {
        List<Organizador> organizadores = controller.obtenerTodosLosOrganizadores();
        StringBuilder sb = new StringBuilder();

        for (Organizador organizador : organizadores) {
            sb.append("Nº Organizador: ").append(organizador.getNOrganizador()).append("\n");
            sb.append("Paga Reserva: ").append(organizador.getPagaReserva()).append("\n");
            sb.append("Nombre: ").append(organizador.getNombre()).append("\n");
            sb.append("Teléfono: ").append(organizador.getTelefono()).append("\n");
            sb.append("Dirección: ").append(organizador.getDireccion()).append("\n");
            sb.append("Nombre Cumpleañero: ").append(organizador.getNombreCumpleanero()).append("\n");
            sb.append("------------------------\n");
        }

        textArea.setText(sb.toString());
    }


    private void agregarOrganizadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarOrganizadorButtonActionPerformed
        insertarOrganizador();
    }//GEN-LAST:event_agregarOrganizadorButtonActionPerformed

    private void eliminarOrganizadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarOrganizadorButtonActionPerformed
        eliminarOrganizador();
    }//GEN-LAST:event_eliminarOrganizadorButtonActionPerformed

    private void obtenerOrganizadoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerOrganizadoresButtonActionPerformed
        mostrarOrganizadores();
    }//GEN-LAST:event_obtenerOrganizadoresButtonActionPerformed

    /**
     * Inserta un nuevo organizador en la base de datos y muestra la lista actualizada.
     */
    public void insertarOrganizador() {
        JTextField nOrganizadorField = new JTextField();
        JTextField pagaReservaField = new JTextField();
        JTextField nombreField = new JTextField();
        JTextField telefonoField = new JTextField();
        JTextField direccionField = new JTextField();
        JTextField nombreCumpleaneroField = new JTextField();

        JPanel inputPanel = new JPanel(new GridLayout(6, 2));
        inputPanel.add(new JLabel("Nº Organizador:"));
        inputPanel.add(nOrganizadorField);
        inputPanel.add(new JLabel("Paga Reserva:"));
        inputPanel.add(pagaReservaField);
        inputPanel.add(new JLabel("Nombre:"));
        inputPanel.add(nombreField);
        inputPanel.add(new JLabel("Teléfono:"));
        inputPanel.add(telefonoField);
        inputPanel.add(new JLabel("Dirección:"));
        inputPanel.add(direccionField);
        inputPanel.add(new JLabel("Nombre Cumpleañero:"));
        inputPanel.add(nombreCumpleaneroField);

        int result = JOptionPane.showConfirmDialog(null, inputPanel, "Agregar Organizador", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                int nOrganizador = Integer.parseInt(nOrganizadorField.getText());
                int pagaReserva = Integer.parseInt(pagaReservaField.getText());
                String nombre = nombreField.getText();
                int telefono = Integer.parseInt(telefonoField.getText());
                String direccion = direccionField.getText();
                String nombreCumpleanero = nombreCumpleaneroField.getText();

                Organizador organizador = new Organizador(nOrganizador, pagaReserva, nombre, telefono, direccion, nombreCumpleanero);
                controller.insertarOrganizador(organizador);
                mostrarOrganizadores();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El número de organizador debe ser un valor entero.");
            }
        }
    }
    
    /**
     * Elimina un organizador de la base de datos y muestra la lista actualizada.
     */
    public void eliminarOrganizador() {
        String nOrganizadorStr = JOptionPane.showInputDialog(null, "Ingrese el número de organizador a eliminar:");
        if (nOrganizadorStr != null) {
            try {
                int nOrganizador = Integer.parseInt(nOrganizadorStr);
                controller.eliminarOrganizador(nOrganizador);
                mostrarOrganizadores();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El número de organizador debe ser un valor entero.");
            }
        }
    }

    /**
     * Método principal que crea una nueva instancia de la vista y la hace visible.
     * 
     * @param args los argumentos de la línea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarOrganizadorButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton eliminarOrganizadorButton;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton obtenerOrganizadoresButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
